id: P009656
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG01613
  title: ཤངས་ལུགས་མཁའ་སྤྱོད་དམར་མོའི་ཚེས་བཅུའི་མཆོད་པ་འདོན་འགྲིགས་བལྟས་ཆོག་ཏུ་བཀོད་པ
  author: ''
  volumes:
    99cfa058724c4df6a76f33fee6cfca8e:
      image_group_id: I00KG02864
      title: ''
      volume_number: 1
      total_pages: 20
      base_file: v001.txt
