id: P009656
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-19 20:43:07.605579
source_metadata:
  id: bdr:W00KG01613
  title: ཤངས་ལུགས་མཁའ་སྤྱོད་དམར་མོའི་ཚེས་བཅུའི་མཆོད་པ་འདོན་འགྲིགས་བལྟས་ཆོག་ཏུ་བཀོད་པ
  author: ''
  volumes:
    99cfa058724c4df6a76f33fee6cfca8e:
      image_group_id: I00KG02864
      title: ''
      volume_number: 1
      total_pages: 20
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
